# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 468a5186ffd19b48aab4abc5c01ac9bf031e34cac832606dc0006748291252b430443665bfbd1401ff330bdb174ec324dd3e88e8fc8fbf67ac857df6fa5eaa85
  app_id: <%= ENV["APPID"] %>
  app_key: <%= ENV["APPKEY"] %>
  aws_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>

test:
  secret_key_base: e90d447b6a227263ee21c1c7dca13b752b6e22f621d427e1587753bed5ab03fc4bcfd9cf779143dfa5ded2e193e9d57de47b018d45ea34e0443cd36c618aed6a
  app_id: <%= ENV["APPID"] %>
  app_key: <%= ENV["APPKEY"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_id: <%= ENV["APPID"] %>
  app_key: <%= ENV["APPKEY"] %>
  aws_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
